### PR TITLE
Adds channels.invite API request

### LINKED ISSUE #195: Channel.Invite Missing
No functionality into channel.invite API endpoint

### PR DESCRIPTION
**Pull request by EasyAsABC123**
This adds the ability to call [channels.invite](https://api.slack.com/methods/channels.invite)

Closes #195

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
@Inumedia any idea when this might be merged?

**Comment by Inumedia** [comment]
Sorry for the delay, been busy

**Comment by EasyAsABC123** [comment]
@Inumedia can you please publish this to nuget?

**Comment by Inumedia** [comment]
Yes, I plan on publishing this today after I get a fix in for the new
`search_sort` issue

**Comment by Inumedia** [comment]
Hi, this should is available in https://www.nuget.org/packages/SlackAPI/1.1.2

**Pull request merged**
