### PR TITLE
Fix for lock async methods on framework

### PR DESCRIPTION
**Pull request by RomanSoloweow**
I have some lock on framework. It's PR fix it

### CODE REVIEW

**Comment by RomanSoloweow** [comment]
@Inumedia  what you think about it?

**Review by Inumedia — APPROVED** [review]
Thanks, this looks a lot better than the old PR

**Comment by RomanSoloweow** [comment]
@Inumedia can you merg it?

**Comment by RomanSoloweow** [comment]
When it will be merged?

**Pull request merged**
