### PR TITLE
Allow limit and cursor on calls with pagination. General cleanup of u…

### PR DESCRIPTION
**Pull request by alexherreid**
Adds the ability to request number of return groups/users/channels in a given request, plus supports the cursor to get additional pages. Assorted string formatting and file cleanup.

### CODE REVIEW

**Comment by alexherreid** [comment]
#230 would be resolved by this

**Comment by Inumedia** [comment]
While I'm sure this does fix the pagination issue, this also applies a lot of styling changes across the board. I can't accept it as is.

**Comment by alexherreid** [comment]
Thanks for the reply. Could you help me better understand why the additional cleanup/styling is a bad thing/undesired? All tests still pass, it adds the missing feature, and those changes help provide cleanup and correct some coding conventions along the way.

**Comment by gpailler** [comment]
I guess @Inumedia expects 2 PR for this kind of change
- One with the fix for the pagination
- One for the code styling changes

It's better to have a specific purpose per PR (easier to track and manage).
Usually, the idea is to adapt the PR to the existing code style (even if the styling is not perfect in the SlackAPI codebase 😄 ) and discuss with the maintainer before a global styling changes.

**Comment by Inumedia** [comment]
Ah, sorry for the confusion!

Yeah, it's exactly as @gpailler says. I'm all for improving code quality and conventions, and improvements in general, but this PR has a lot of changes and causes conflicts with other PRs I merged earlier.

If you need pagination implemented asap, I suggest creating a pull request with just those required changes.

As for the conventions, those should be in their own PR and maybe some discussion around them.

**Comment by Inumedia** [comment]
Closed due to inactivity from PR author, please submit two new PRs one for style and one for pagination

**Pull request closed without merging**
