### PR TITLE
Adding as_user parameter in PostMessage method.

### PR DESCRIPTION
**Pull request by matheusriboli**

### CODE REVIEW

**Comment by Inumedia** [comment]
Hi, could you add a short description to this pull request?

**Comment by matheusriboli** [comment]
Hi.
Slack API has a 'as_user' field in the chat.postMessage method.
The official documentation says: "Pass true to post the message as the authed user, instead of as a bot".
Ref: https://api.slack.com/methods/chat.postMessage

**Comment by Inumedia** [comment]
Oh, neat. That basically removes the requirement of using a web socket to post as yourself.

**Comment by Inumedia** [comment]
Thanks :)

**Comment by matheusriboli** [comment]
;)

**Pull request merged**
