### PR TITLE
fix Nre - https://github.com/Inumedia/SlackAPI/issues/109

### PR DESCRIPTION
**Pull request by koderhari**

### CODE REVIEW

**Comment by dicko2** [comment]
We are facing this problem as well, can you please advise when this will be merged in?

**Comment by andymac4182** [comment]
Hey @dicko2 
@koderhari will probably need to resolve the build issues if possible first.

**Comment by dicko2** [comment]
haha nice to hear from you @andymac4182 

```
Cake.exe : Error: The assembly 'MagicChunks.Cake, Version=1.2.0.58, Culture=neutral, PublicKeyToken=null' 
At line:1 char:1
```

Error is nothing to do with the code. I did fork this library once before, looks like i'll have to do it again to fix it :(

**Comment by dicko2** [comment]
For the record, we get our bot crash consistently every 2-3 days, and we "notice" because our bnot does the merging to master for us :) no exceptions, and nothing in the console output on kestral (just checked again from the crash today). So i am 99% sure this one is our problem

**Pull request merged**
