### PR TITLE
Editable APIBaseLocation in SlackClientBase

### PR DESCRIPTION
**Pull request by Xanrum**
Our organization uses proxies to access the Slack API. We need the ability to edit the address.

### CODE REVIEW

**Comment by gpailler** [comment]
Hi @Xanrum . Using an IWebProxy instance to configure your proxy doesn't work in your case?

https://github.com/Inumedia/SlackAPI/blob/4877988523d6cf7ffe31c7f9c94007b995a29729/SlackAPI/SlackSocketClient.cs#L29

**Comment by Xanrum** [comment]
For example url of this proxy: https://infra.exmple.com/exmaple-team/slack/

**Comment by gpailler** [comment]
I'm just curious. Is it a homemade solution created by your organization to monitor https traffic or is it something provided by a third-party company?

**Comment by Xanrum** [comment]
Yes you are right. The security department wants to read the messaging.

**Pull request merged**
